// 운동 종목 데이터베이스 (이름, 주동근, 보조근, 장비)
export const EXERCISE_DB = [
  // 가슴
  { name:'벤치프레스',       primary:['가슴'],         secondary:['어깨','삼두'],    eq:'바벨' },
  { name:'인클라인 벤치프레스', primary:['가슴'],      secondary:['어깨','삼두'],    eq:'바벨' },
  { name:'덤벨 플라이',      primary:['가슴'],         secondary:['어깨'],           eq:'덤벨' },
  { name:'푸시업',           primary:['가슴'],         secondary:['어깨','삼두','코어'], eq:'맨몸' },
  { name:'딥스',             primary:['가슴','삼두'],  secondary:['어깨'],           eq:'맨몸' },
  { name:'케이블 크로스오버', primary:['가슴'],        secondary:['어깨'],           eq:'케이블' },
  { name:'체스트 프레스 머신', primary:['가슴'],       secondary:['어깨','삼두'],    eq:'머신' },
  // 등
  { name:'풀업',             primary:['등'],           secondary:['이두','어깨'],    eq:'맨몸' },
  { name:'랫풀다운',         primary:['등'],           secondary:['이두','어깨'],    eq:'케이블' },
  { name:'바벨 로우',        primary:['등'],           secondary:['이두','코어'],    eq:'바벨' },
  { name:'덤벨 로우',        primary:['등'],           secondary:['이두','어깨'],    eq:'덤벨' },
  { name:'시티드 케이블 로우', primary:['등'],         secondary:['이두'],           eq:'케이블' },
  { name:'데드리프트',       primary:['등','하체'],    secondary:['코어','어깨'],    eq:'바벨' },
  { name:'루마니안 데드리프트', primary:['하체','등'], secondary:['코어'],           eq:'바벨' },
  { name:'로잉 머신',        primary:['유산소','등'],  secondary:['이두','하체','코어'], eq:'머신' },
  // 어깨
  { name:'바벨 숄더프레스',  primary:['어깨'],         secondary:['삼두'],           eq:'바벨' },
  { name:'덤벨 숄더프레스',  primary:['어깨'],         secondary:['삼두'],           eq:'덤벨' },
  { name:'레터럴 레이즈',    primary:['어깨'],         secondary:[],                 eq:'덤벨' },
  { name:'프론트 레이즈',    primary:['어깨'],         secondary:[],                 eq:'덤벨' },
  { name:'페이스풀',         primary:['어깨'],         secondary:['이두'],           eq:'케이블' },
  { name:'업라이트 로우',    primary:['어깨'],         secondary:['이두'],           eq:'바벨' },
  { name:'리어 델트 플라이', primary:['어깨'],         secondary:['등'],             eq:'덤벨' },
  // 이두
  { name:'바벨 컬',          primary:['이두'],         secondary:[],                 eq:'바벨' },
  { name:'덤벨 컬',          primary:['이두'],         secondary:[],                 eq:'덤벨' },
  { name:'해머 컬',          primary:['이두'],         secondary:[],                 eq:'덤벨' },
  { name:'케이블 컬',        primary:['이두'],         secondary:[],                 eq:'케이블' },
  { name:'인클라인 덤벨 컬', primary:['이두'],         secondary:[],                 eq:'덤벨' },
  { name:'컨센트레이션 컬',  primary:['이두'],         secondary:[],                 eq:'덤벨' },
  { name:'프리처 컬',        primary:['이두'],         secondary:[],                 eq:'바벨' },
  // 삼두
  { name:'케이블 푸시다운',  primary:['삼두'],         secondary:[],                 eq:'케이블' },
  { name:'스컬 크러셔',      primary:['삼두'],         secondary:[],                 eq:'바벨' },
  { name:'오버헤드 트라이셉스 익스텐션', primary:['삼두'], secondary:[],             eq:'덤벨' },
  { name:'클로즈그립 벤치프레스', primary:['삼두','가슴'], secondary:['어깨'],      eq:'바벨' },
  { name:'킥백',             primary:['삼두'],         secondary:[],                 eq:'덤벨' },
  // 하체
  { name:'스쿼트',           primary:['하체'],         secondary:['코어','등'],      eq:'바벨' },
  { name:'레그프레스',       primary:['하체'],         secondary:[],                 eq:'머신' },
  { name:'런지',             primary:['하체'],         secondary:['코어'],           eq:'맨몸' },
  { name:'불가리안 스플릿 스쿼트', primary:['하체'],  secondary:['코어'],           eq:'덤벨' },
  { name:'레그 익스텐션',    primary:['하체'],         secondary:[],                 eq:'머신' },
  { name:'레그 컬',          primary:['하체'],         secondary:[],                 eq:'머신' },
  { name:'힙쓰러스트',       primary:['하체'],         secondary:['코어'],           eq:'바벨' },
  { name:'카프 레이즈',      primary:['하체'],         secondary:[],                 eq:'맨몸' },
  { name:'케틀벨 스윙',      primary:['하체','등'],    secondary:['코어','어깨'],    eq:'케틀벨' },
  { name:'박스 점프',        primary:['유산소','하체'], secondary:['코어'],          eq:'맨몸' },
  // 코어
  { name:'플랭크',           primary:['코어'],         secondary:['어깨','등'],      eq:'맨몸' },
  { name:'사이드 플랭크',    primary:['코어'],         secondary:[],                 eq:'맨몸' },
  { name:'크런치',           primary:['코어'],         secondary:[],                 eq:'맨몸' },
  { name:'레그 레이즈',      primary:['코어'],         secondary:[],                 eq:'맨몸' },
  { name:'러시안 트위스트',  primary:['코어'],         secondary:[],                 eq:'맨몸' },
  { name:'AB 롤아웃',        primary:['코어'],         secondary:['어깨','등'],      eq:'롤러' },
  { name:'케이블 크런치',    primary:['코어'],         secondary:[],                 eq:'케이블' },
  { name:'마운틴 클라이머',  primary:['유산소','코어'], secondary:['어깨'],          eq:'맨몸' },
  // 유산소
  { name:'러닝',             primary:['유산소'],       secondary:['하체'],           eq:'-' },
  { name:'자전거 (실내)',     primary:['유산소'],       secondary:['하체'],           eq:'-' },
  { name:'줄넘기',           primary:['유산소'],       secondary:['하체','코어'],    eq:'-' },
  { name:'버피',             primary:['유산소','코어'], secondary:['가슴','어깨'],   eq:'맨몸' },
  { name:'점핑잭',           primary:['유산소'],       secondary:['어깨','하체'],    eq:'맨몸' },
  { name:'팔 벌려뛰기',      primary:['유산소'],       secondary:['어깨','하체'],    eq:'맨몸' },
  { name:'스텝퍼',           primary:['유산소','하체'], secondary:[],                eq:'머신' },
  { name:'일립티컬',         primary:['유산소'],       secondary:['하체','코어'],    eq:'머신' },
]
